import { g } from 'genshin-ts/runtime/core'
import * as E from 'genshin-ts/definitions/enum'

// AUTO-GENERATED enum coverage for enumerationsEqual
// Run: npx tsx scripts/generate-enum-gia-tests.ts

g.server({ id: 1073741858 }).on('whenEntityIsCreated', (_evt, f) => {
  // SortBy
  f.enumerationsEqual(E.SortBy.Ascending, E.SortBy.Ascending)
  f.enumerationsEqual(E.SortBy.Ascending, E.SortBy.Descending)
  // FollowCoordinateSystem
  f.enumerationsEqual(E.FollowCoordinateSystem.RelativeCoordinateSystem, E.FollowCoordinateSystem.RelativeCoordinateSystem)
  f.enumerationsEqual(E.FollowCoordinateSystem.RelativeCoordinateSystem, E.FollowCoordinateSystem.WorldCoordinateSystem)
  // FollowLocationType
  f.enumerationsEqual(E.FollowLocationType.CompletelyFollow, E.FollowLocationType.CompletelyFollow)
  f.enumerationsEqual(E.FollowLocationType.CompletelyFollow, E.FollowLocationType.FollowLocation)
  // UIControlGroupStatus
  f.enumerationsEqual(E.UIControlGroupStatus.Off, E.UIControlGroupStatus.Off)
  f.enumerationsEqual(E.UIControlGroupStatus.Off, E.UIControlGroupStatus.On)
  // DisruptorDeviceType
  f.enumerationsEqual(E.DisruptorDeviceType.ForceFieldDevice, E.DisruptorDeviceType.ForceFieldDevice)
  f.enumerationsEqual(E.DisruptorDeviceType.ForceFieldDevice, E.DisruptorDeviceType.Ejector)
  // DisruptorDeviceOrientation
  f.enumerationsEqual(E.DisruptorDeviceOrientation.AssociateCharacterOrientation, E.DisruptorDeviceOrientation.AssociateCharacterOrientation)
  f.enumerationsEqual(E.DisruptorDeviceOrientation.AssociateCharacterOrientation, E.DisruptorDeviceOrientation.FixedUnidirectional)
  // CharacterSkillSlot
  f.enumerationsEqual(E.CharacterSkillSlot.NormalAttack, E.CharacterSkillSlot.NormalAttack)
  f.enumerationsEqual(E.CharacterSkillSlot.NormalAttack, E.CharacterSkillSlot.Skill1E)
  // SoundAttenuationMode
  f.enumerationsEqual(E.SoundAttenuationMode.LinearAttenuation, E.SoundAttenuationMode.LinearAttenuation)
  f.enumerationsEqual(E.SoundAttenuationMode.LinearAttenuation, E.SoundAttenuationMode.FastThenSlow)
  // LogicalOperator
  f.enumerationsEqual(E.LogicalOperator.AND, E.LogicalOperator.AND)
  f.enumerationsEqual(E.LogicalOperator.AND, E.LogicalOperator.OR)
  // MathematicalOperator
  f.enumerationsEqual(E.MathematicalOperator.Addition, E.MathematicalOperator.Addition)
  f.enumerationsEqual(E.MathematicalOperator.Addition, E.MathematicalOperator.Subtraction)
  // TrigonometricFunction
  f.enumerationsEqual(E.TrigonometricFunction.Cos, E.TrigonometricFunction.Cos)
  f.enumerationsEqual(E.TrigonometricFunction.Cos, E.TrigonometricFunction.Sin)
  // AttackShape
  f.enumerationsEqual(E.AttackShape.Rectangle, E.AttackShape.Rectangle)
  f.enumerationsEqual(E.AttackShape.Rectangle, E.AttackShape.Sphere)
  // SurvivalStatus
  f.enumerationsEqual(E.SurvivalStatus.Alive, E.SurvivalStatus.Alive)
  f.enumerationsEqual(E.SurvivalStatus.Alive, E.SurvivalStatus.Down)
  // TypeConversion
  f.enumerationsEqual(E.TypeConversion.IntegerToBoolean, E.TypeConversion.IntegerToBoolean)
  f.enumerationsEqual(E.TypeConversion.IntegerToBoolean, E.TypeConversion.IntegerToFloatingPoint)
  // MotionPathPointType
  f.enumerationsEqual(E.MotionPathPointType.StraightLine, E.MotionPathPointType.StraightLine)
  f.enumerationsEqual(E.MotionPathPointType.StraightLine, E.MotionPathPointType.Curve)
  // MotionType
  f.enumerationsEqual(E.MotionType.OneWay, E.MotionType.OneWay)
  f.enumerationsEqual(E.MotionType.OneWay, E.MotionType.BackAndForth)
  // DecisionRefreshMode
  f.enumerationsEqual(E.DecisionRefreshMode.CannotRefresh, E.DecisionRefreshMode.CannotRefresh)
  f.enumerationsEqual(E.DecisionRefreshMode.CannotRefresh, E.DecisionRefreshMode.PartialRefresh)
  // SettlementStatus
  f.enumerationsEqual(E.SettlementStatus.Undefined, E.SettlementStatus.Undefined)
  f.enumerationsEqual(E.SettlementStatus.Undefined, E.SettlementStatus.Victory)
  // ItemLootType
  f.enumerationsEqual(E.ItemLootType.SharedReward, E.ItemLootType.SharedReward)
  f.enumerationsEqual(E.ItemLootType.SharedReward, E.ItemLootType.IndividualizedReward)
  // RoundingMode
  f.enumerationsEqual(E.RoundingMode.RoundToNearest, E.RoundingMode.RoundToNearest)
  f.enumerationsEqual(E.RoundingMode.RoundToNearest, E.RoundingMode.RoundUp)
  // EntityType
  f.enumerationsEqual(E.EntityType.Stage, E.EntityType.Stage)
  f.enumerationsEqual(E.EntityType.Stage, E.EntityType.Object)
  // ComparisonOperator
  f.enumerationsEqual(E.ComparisonOperator.EqualTo, E.ComparisonOperator.EqualTo)
  f.enumerationsEqual(E.ComparisonOperator.EqualTo, E.ComparisonOperator.LessThan)
  // CauseOfBeingDown
  f.enumerationsEqual(E.CauseOfBeingDown.NodeGraphTriggered, E.CauseOfBeingDown.NodeGraphTriggered)
  f.enumerationsEqual(E.CauseOfBeingDown.NodeGraphTriggered, E.CauseOfBeingDown.NormalDefeat)
  // ElementalType
  f.enumerationsEqual(E.ElementalType.None, E.ElementalType.None)
  f.enumerationsEqual(E.ElementalType.None, E.ElementalType.Pyro)
  // UnitStatusRemovalReason
  f.enumerationsEqual(E.UnitStatusRemovalReason.ReplacedByOtherUnitStatus, E.UnitStatusRemovalReason.ReplacedByOtherUnitStatus)
  f.enumerationsEqual(E.UnitStatusRemovalReason.ReplacedByOtherUnitStatus, E.UnitStatusRemovalReason.DurationExceeded)
  // ElementalReactionType
  f.enumerationsEqual(E.ElementalReactionType.Overloaded, E.ElementalReactionType.Overloaded)
  f.enumerationsEqual(E.ElementalReactionType.Overloaded, E.ElementalReactionType.Vaporize)
  // SelectCompletionReason
  f.enumerationsEqual(E.SelectCompletionReason.CompletedByPlayer, E.SelectCompletionReason.CompletedByPlayer)
  f.enumerationsEqual(E.SelectCompletionReason.CompletedByPlayer, E.SelectCompletionReason.Timeout)
  // ReasonForItemChange
  f.enumerationsEqual(E.ReasonForItemChange.Destroy, E.ReasonForItemChange.Destroy)
  f.enumerationsEqual(E.ReasonForItemChange.Destroy, E.ReasonForItemChange.Discard)
  // TargetType
  f.enumerationsEqual(E.TargetType.None, E.TargetType.None)
  f.enumerationsEqual(E.TargetType.None, E.TargetType.AlliedFaction)
  // TriggerRestriction
  f.enumerationsEqual(E.TriggerRestriction.TriggerOnlyOnce, E.TriggerRestriction.TriggerOnlyOnce)
  f.enumerationsEqual(E.TriggerRestriction.TriggerOnlyOnce, E.TriggerRestriction.TriggerOnlyOncePerEntity)
  // HitType
  f.enumerationsEqual(E.HitType.None, E.HitType.None)
  f.enumerationsEqual(E.HitType.None, E.HitType.Default)
  // AttackType
  f.enumerationsEqual(E.AttackType.None, E.AttackType.None)
  f.enumerationsEqual(E.AttackType.None, E.AttackType.MeleeAttack)
  // HitPerformanceLevel
  f.enumerationsEqual(E.HitPerformanceLevel.Default, E.HitPerformanceLevel.Default)
  f.enumerationsEqual(E.HitPerformanceLevel.Default, E.HitPerformanceLevel.NoHitPerformance)
  // UnitStatusAdditionResult
  f.enumerationsEqual(E.UnitStatusAdditionResult.FailedUnexpectedError, E.UnitStatusAdditionResult.FailedUnexpectedError)
  f.enumerationsEqual(E.UnitStatusAdditionResult.FailedUnexpectedError, E.UnitStatusAdditionResult.FailedOperationPausedForAnotherProcess)
  // UnitStatusRemovalStrategy
  f.enumerationsEqual(E.UnitStatusRemovalStrategy.AllCoexistingStatusesWithTheSameName, E.UnitStatusRemovalStrategy.AllCoexistingStatusesWithTheSameName)
  f.enumerationsEqual(E.UnitStatusRemovalStrategy.AllCoexistingStatusesWithTheSameName, E.UnitStatusRemovalStrategy.StatusWithFastestStackLoss)
  // RevivePointSelectionStrategy
  f.enumerationsEqual(E.RevivePointSelectionStrategy.Nearest, E.RevivePointSelectionStrategy.Nearest)
  f.enumerationsEqual(E.RevivePointSelectionStrategy.Nearest, E.RevivePointSelectionStrategy.MostRecentlyActivated)
  // InterruptStatus
  f.enumerationsEqual(E.InterruptStatus.InterruptResistanceStatus, E.InterruptStatus.InterruptResistanceStatus)
  f.enumerationsEqual(E.InterruptStatus.InterruptResistanceStatus, E.InterruptStatus.InterruptVulnerabilityStatus)
  // GameplayMode
  f.enumerationsEqual(E.GameplayMode.Play, E.GameplayMode.Play)
  f.enumerationsEqual(E.GameplayMode.Play, E.GameplayMode.RoomPlay)
  // InputDeviceType
  f.enumerationsEqual(E.InputDeviceType.KeyboardAndMouse, E.InputDeviceType.KeyboardAndMouse)
  f.enumerationsEqual(E.InputDeviceType.KeyboardAndMouse, E.InputDeviceType.Controller)
})
